### ISSUE TITLE
Email sink printing password on logs when it cannot connect to the server !!

### ISSUE THREAD

**Issue by suhothayan** [wso2-extensions/siddhi-io-email#15]
**Description:**
This happens when passwords in added to .yaml file in SP

Cannot assign to ChathurikaA for some reason. !

-----------

[2017-11-02 00:38:56,368] ERROR {org.wso2.siddhi.core.stream.output.sink.Sink} - Error on 'Sweet-Factory-Analytics'. Error is encountered while connecting to the server with properties: {password=yyyyyy, mail.smtp.port=465, mail.smtp.auth=true, mail.smtp.host=smtp.gmail.com, username=xxx, mail.smtp.ssl.enable=true} Error while connecting at Sink 'email' at 'SLAAlertStream'. java.lang.RuntimeException: Error is encountered while connecting to the server with properties: {password=yyyyyy, mail.smtp.port=465, mail.smtp.auth=true, mail.smtp.host=smtp.gmail.com, username=xxx, mail.smtp.ssl.enable=true}
	at org.wso2.extension.siddhi.io.email.sink.EmailSink.connect(EmailSink.java:371)
	at org.wso2.siddhi.core.stream.output.sink.Sink.connectWithRetry(Sink.java:177)
	at org.wso2.siddhi.core.SiddhiAppRuntime.start(SiddhiAppRuntime.java:285)
	at org.wso2.carbon.siddhi.editor.core.internal.DebugRuntime.start(DebugRuntime.java:64)
	at org.wso2.carbon.siddhi.editor.core.internal.DebugProcessorService.start(DebugProcessorService.java:37)
	at org.wso2.carbon.siddhi.editor.core.internal.ServiceComponent.start(ServiceComponent.java:482)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:248)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.lambda$receive$73(MSF4JMessageProcessor.java:160)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.messaging.exceptions.ClientConnectorException: Error is encountered while creating  the connection using the session.535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials z2sm2539509pgo.54 - gsmtp

	at org.wso2.carbon.transport.email.sender.EmailClientConnector.init(EmailClientConnector.java:98)
	at org.wso2.extension.siddhi.io.email.sink.EmailSink.connect(EmailSink.java:358)
	... 16 more
Caused by: javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials z2sm2539509pgo.54 - gsmtp

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:932)
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:843)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:748)
	at javax.mail.Service.connect(Service.java:388)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at org.wso2.carbon.transport.email.sender.EmailClientConnector.init(EmailClientConnector.java:92)
	... 17 more

**Comment by mohanvive** [comment]
@suhothayan , seems like above is already fixed in a previous commit. 

https://github.com/wso2-extensions/siddhi-io-email/commit/728f931161077465906db6dcf6bc1387d06fc75e
