### ISSUE TITLE
analytics worker wso2 3.2.0 siddhi mail not generating for outlook

### ISSUE THREAD

**Issue by kalevivek11** [wso2-extensions/siddhi-io-email#65]
I have configured the below section under siddhi in wso2 YAML file of the analytics worker, it works only for Gmail not for outlook any thoughts on this

**this works fine**
extension:
            name: email
            namespace: sink
            properties:
              username: wso2test9@gmail.com
              address: wso2test9@gmail.com
              password: *******@12

**this does not work**
 -
      extension:
            name: email
            namespace: sink
            properties:
              username: xx.machine@oo.com
              address:  xx.machine@oo.com
              password: *****!

Error
ERROR {io.siddhi.core.stream.output.sink.Sink} - Error on 'APIM_ALERT_EMAIL_NOTIFICATION'. Error is encountered while connecting to the the smtp server.Error is encountered while creating  the connection using the session.535-5.7.8 Username and Password not accepted. Learn more at_535 5.7.8  https://support.google.com/mail/?p=BadCredentials ca6sm5486641pjb.53 - gsmtp_, error while connecting at Sink 'email' at 'EmailNotificationStream'. java.lang.RuntimeException: Error is encountered while connecting to the the smtp server.Error is encountered while creating  the connection using the session.535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials ca6sm5486641pjb.53 - gsmtp

        at io.siddhi.extension.io.email.sink.EmailSink.connect(EmailSink.java:496)
        at io.siddhi.core.stream.output.sink.Sink.connectWithRetry(Sink.java:254)
        at io.siddhi.core.SiddhiAppRuntimeImpl.startWithoutSources(SiddhiAppRuntimeImpl.java:451)
        at io.siddhi.core.SiddhiAppRuntimeImpl.start(SiddhiAppRuntimeImpl.java:424)
        at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorService.deploySiddhiApp(StreamProcessorService.java:215)
        at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorDeployer.deploySiddhiQLFile(StreamProcessorDeployer.java:95)
        at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorDeployer.deploy(StreamProcessorDeployer.java:330)
        at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.lambda$deployArtifacts$0(DeploymentEngine.java:291)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.deployArtifacts(DeploymentEngine.java:282)
        at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.sweep(RepositoryScanner.java:112)
        at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.scan(RepositoryScanner.java:68)
        at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.start(DeploymentEngine.java:121)
        at org.wso2.carbon.deployment.engine.internal.DeploymentEngineListenerComponent.onAllRequiredCapabilitiesAvailable(DeploymentEngineListenerComponent.java:216)
        at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$7(StartupComponentManager.java:266)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:252)
        at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:204)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: org.wso2.transport.email.exception.EmailConnectorException: Error is encountered while creating  the connection using the session.535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials ca6sm5486641pjb.53 - gsmtp

        at org.wso2.transport.email.client.connector.EmailClientConnectorImpl.init(EmailClientConnectorImpl.java:139)
        at io.siddhi.extension.io.email.sink.EmailSink.connect(EmailSink.java:484)
        ... 19 more
Caused by: javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials ca6sm5486641pjb.53 - gsmtp

        at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:932)
        at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:843)
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:748)
        at javax.mail.Service.connect(Service.java:388)
        at javax.mail.Service.connect(Service.java:246)
        at javax.mail.Service.connect(Service.java:195)
        at org.wso2.transport.email.client.connector.EmailClientConnectorImpl.init(EmailClientConnectorImpl.java:133)
        ... 20 more

[2020-09-17 16:18:07,921] ERROR {io.siddhi.core.SiddhiAppRuntimeImpl} - Error starting Siddhi App 'APIM_ALERT_EMAIL_NOTIFICATION', triggering shutdown process. Error is encountered while connecting to the the smtp server.Error is encountered while creating  the connection using the session.535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials ca6sm5486641pjb.53 - gsmtp

[2020-09-17 16:18:07,929]  INFO {org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorService} - Siddhi App APIM_ALERT_EMAIL_NOTIFICATION deployed successfully
[2020-09-17 16:18:07,937]  INFO {org.wso2.carbon.kernel.internal.CarbonStartupHandler} - WSO2 API Manager Analytics Server started in 44.888 sec

**Comment by kalevivek11** [comment]
@RAVEENSR   Any update on this??
